services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blogdb
    depends_on:
      - db
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: restart
          path: ./backend/src
        - action: rebuild
          path: ./backend/Dockerfile

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: